apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-cleaner
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-cleaner
subjects:
- kind: ServiceAccount
  name: jobs-cleaner
  namespace: production
